# Generated by Django 2.2.6 on 2020-04-15 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0002_auto_20200415_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='owner',
        ),
    ]
