# Generated by Django 2.2.6 on 2020-04-15 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0003_remove_products_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='owner',
        ),
    ]
