"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 2.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'vic1tjxyip&*lx^kjybo12r6in)906fc$nifb%tyqs+u0lcc$*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    #Imported Modules
    'rest_framework',
    'graphene_django',
    'autofixture',

    #Created Apps
    'apps.buy',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = "config.routing.application"

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases


DATABASES = {
    "default": {
        "ENGINE": os.environ.get("SQL_ENGINE", "django.db.backends.sqlite3"),
        "NAME": os.environ.get("SQL_DATABASE", os.path.join(BASE_DIR, "db.sqlite3")),
        "USER": os.environ.get("SQL_USER", "user"),
        "PASSWORD": os.environ.get("SQL_PASSWORD", "password"),
        "HOST": os.environ.get("SQL_HOST", "localhost"),
        "PORT": os.environ.get("SQL_PORT", "5432"),
    }
}



# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
# static file directory
STATIC_ROOT = os.path.join(BASE_DIR, "static_files")
# define the media root, where all the uploaded files will be put
MEDIA_ROOT = os.path.join(BASE_DIR, "uploaded_files")
# static file directory
STATIC_ROOT = "/static_files"
# define the media root, where all the uploaded files will be put
MEDIA_ROOT = "/uploaded_files"

# Graphql
GRAPHENE = { 'SCHEMA': 'config.schema.schema', }

# Logging

LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'formatters': {
            'request_format': {
                'format': '%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d (%(message)s) '
                          '%(remote_addr)s %(user_id)s "%(request_method)s '
                          '%(path_info)s %(server_protocol)s" %(http_user_agent)s ',
            },
            'verbose': {
                'format': '%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d (%(message)s) '
            },
        },
        'handlers': {
            'console_django': {
                'class': 'logging.StreamHandler',
                # 'filters': ['request'],
                'formatter': 'verbose',
            },
            'console_project': {
                'class': 'logging.StreamHandler',
                # 'filters': ['request'],
                'formatter': 'request_format',
            },
            'file': {
                'class': 'logging.FileHandler',
                'filename': BASE_DIR + '/' + 'debug.log'
            },
        },
        'loggers': {
            'django.server': {
                'level': 'DEBUG',
                'handlers': ['console_django'],

            },
            'django.request': {
                'level': 'DEBUG',
                'handlers': ['console_django'],
            },
            'apps': {
                'level': 'DEBUG',
                'handlers': ['file', 'console_django'],
            }
        },
    }